(str) @string
(num) @constant
(dot) @punctuation
(hash) @label
(esc) @punctuation
(def) @punctuation
(var) @punctuation
(mstr) @punctuation
(brack) @punctuation
(word) @function
(cmd) @operator
(name) @keyword
